complete -c skifflm -l help -d 'Show help'
complete -c skifflm -l version -d 'Show version'
complete -c skifflm -l show-config -d 'Print effective configuration'
complete -c skifflm -l list-models -d 'List discovered GGUF models'
complete -c skifflm -l model-info -d 'Print model metadata'
complete -c skifflm -l doctor -d 'Print system diagnostics'
complete -c skifflm -l smoke -d 'Run generation smoke test'
complete -c skifflm -l tokenize -r -d 'Tokenize text'
complete -c skifflm -l warmup -d 'Warm model before first answer'
complete -c skifflm -l attach -r -d 'Attach file'
complete -c skifflm -l file -r -d 'Attach file'
complete -c skifflm -l export -r -d 'Export conversation as Markdown'
complete -c skifflm -l chat-template -r -d 'Override chat template'
complete -c skifflm -l model -r -d 'Path to a GGUF model'
complete -c skifflm -l model-dir -r -d 'Model directory'
complete -c skifflm -l config -r -d 'Config file path'
complete -c skifflm -l history -r -d 'Session history file'
complete -c skifflm -l session -r -d 'Named session'
complete -c skifflm -l profile -r -a 'balanced fast creative code precise' -d 'Sampling profile'
complete -c skifflm -l system -r -d 'System prompt'
complete -c skifflm -l stop -r -d 'Stop sequence'
complete -c skifflm -l output -r -d 'Write answer to file'
complete -c skifflm -l prompt -r -d 'Single prompt'
complete -c skifflm -l prompt-file -r -d 'Read prompt from file'
complete -c skifflm -l stdin -d 'Read prompt from stdin'
complete -c skifflm -l json -d 'JSON output'
complete -c skifflm -l non-interactive -d 'Disable interactive shell'
complete -c skifflm -l ctx -r -d 'Context size'
complete -c skifflm -l batch -r -d 'Batch size'
complete -c skifflm -l ubatch -r -d 'Physical batch size'
complete -c skifflm -l reserve-ctx -r -d 'Reserved context'
complete -c skifflm -l n-keep -r -d 'Kept turns during trimming'
complete -c skifflm -l threads -r -d 'CPU threads'
complete -c skifflm -l gpu-layers -r -d 'GPU layers'
complete -c skifflm -l mmap -d 'Enable mmap'
complete -c skifflm -l no-mmap -d 'Disable mmap'
complete -c skifflm -l mlock -d 'Lock model memory'
complete -c skifflm -l flash-attn -d 'Enable flash attention'
complete -c skifflm -l no-flash-attn -d 'Disable flash attention'
complete -c skifflm -l numa -d 'Enable NUMA optimization'
complete -c skifflm -l kv-offload -d 'Enable KV offload'
complete -c skifflm -l no-kv-offload -d 'Disable KV offload'
complete -c skifflm -l temp -r -d 'Temperature'
complete -c skifflm -l top-p -r -d 'Top-p'
complete -c skifflm -l top-k -r -d 'Top-k'
complete -c skifflm -l min-p -r -d 'Min-p'
complete -c skifflm -l typical -r -d 'Typical sampling'
complete -c skifflm -l repeat-penalty -r -d 'Repeat penalty'
complete -c skifflm -l repeat-last-n -r -d 'Repeat window'
complete -c skifflm -l n-predict -r -d 'Max generated tokens'
complete -c skifflm -l seed -r -d 'Sampling seed'
complete -c skifflm -l reset-history -d 'Reset history'
complete -c skifflm -l no-save -d 'Disable session saving'
complete -c skifflm -l auto-trim -d 'Auto trim context'
complete -c skifflm -l no-auto-trim -d 'Disable auto trim'
complete -c skifflm -l color -d 'Enable color'
complete -c skifflm -l no-color -d 'Disable color'
complete -c skifflm -l no-banner -d 'Hide banner'
complete -c skifflm -l verbose -d 'Verbose logs'
complete -c skifflm -l debug -d 'Debug mode'
