#compdef skifflm

_skifflm() {
    local -a opts
    opts=(
        '--help[Show help]'
        '--version[Show version]'
        '--show-config[Print effective configuration]'
        '--context-bar[Show the live context usage bar]'
        '--no-context-bar[Hide the context usage bar]'
        '--backend-info[Print the active llama.cpp backends]'
        '--list-models[List discovered GGUF models]'
        '--model-info[Print model metadata]'
        '--doctor[Print system diagnostics]'
        '--smoke[Run generation smoke test]'
        '--tokenize[Tokenize text]:text'
        '--warmup[Warm the model before the first answer]'
        '--serve[Serve a local OpenAI-compatible API]'
        '--host[Local server bind address]:host:(127.0.0.1 0.0.0.0 ::1)'
        '--port[Local server port]:integer'
        '--benchmark[Run a real generation benchmark]:integer'
        '--attach[Attach file]:file:_files'
        '--file[Attach file]:file:_files'
        '--export[Export conversation as Markdown]:file:_files'
        '--chat-template[Override chat template]:template:(chatml llama2 mistral gemma phi qwen default)'
        '--model[MGGUF model path]:file:_files'
        '--model-dir[Model directory]:dir:_directories'
        '--config[Config file path]:file:_files'
        '--history[Session history file]:file:_files'
        '--session[Named session]:session'
        '--profile[Sampling profile]:profile:(balanced fast creative code precise)'
        '--system[System prompt]:text'
        '--stop[Stop sequence]:text'
        '--output[Write answer to file]:file:_files'
        '--prompt[Single prompt]:text'
        '--prompt-file[Read prompt from file]:file:_files'
        '--stdin[Read prompt from stdin]'
        '--json[JSON output]'
        '--non-interactive[Disable interactive shell]'
        '--ctx[Context size]:integer'
        '--batch[Batch size]:integer'
        '--ubatch[Physical batch size]:integer'
        '--reserve-ctx[Reserved context]:integer'
        '--n-keep[Kept turns during trimming]:integer'
        '--threads[CPU threads]:integer'
        '--gpu-layers[GPU layers]:integer'
        '--mmap[Enable mmap]'
        '--no-mmap[Disable mmap]'
        '--mlock[Lock model memory]'
        '--flash-attn[Enable flash attention]'
        '--no-flash-attn[Disable flash attention]'
        '--numa[Enable NUMA optimization]'
        '--kv-offload[Enable KV offload]'
        '--no-kv-offload[Disable KV offload]'
        '--temp[Temperature]:float'
        '--top-p[Top-p]:float'
        '--top-k[Top-k]:integer'
        '--min-p[Min-p]:float'
        '--typical[Typical sampling]:float'
        '--repeat-penalty[Repeat penalty]:float'
        '--repeat-last-n[Repeat window]:integer'
        '--n-predict[Max generated tokens]:integer'
        '--seed[Sampling seed]:seed'
        '--reset-history[Reset history]'
        '--no-save[Disable session saving]'
        '--auto-trim[Auto trim context]'
        '--no-auto-trim[Disable auto trim]'
        '--color[Enable color]'
        '--no-color[Disable color]'
        '--no-banner[Hide banner]'
        '--verbose[Verbose logs]'
        '--debug[Debug mode]'
    )
    _arguments "${opts[@]}" '1:subcommand:(run model chat-template config server)' '*:model file:_files'
}

_skifflm "$@"
