complete -c skiffllm -l help -d 'Show help'
complete -c skiffllm -l version -d 'Show version'
complete -c skiffllm -l show-config -d 'Print effective configuration'
complete -c skiffllm -l list-models -d 'List discovered GGUF models'
complete -c skiffllm -l model-info -d 'Print model metadata'
complete -c skiffllm -l doctor -d 'Print system diagnostics'
complete -c skiffllm -l smoke -d 'Run generation smoke test'
complete -c skiffllm -l tokenize -r -d 'Tokenize text'
complete -c skiffllm -l warmup -d 'Warm model before first answer'
complete -c skiffllm -l serve -d 'Serve a local OpenAI-compatible API'
complete -c skiffllm -l host -r -d 'Local server bind address'
complete -c skiffllm -l port -r -d 'Local server port'
complete -c skiffllm -l api-key -r -d 'Bearer token required by the local server'
complete -c skiffllm -l benchmark -r -d 'Run a real generation benchmark'
complete -c skiffllm -l attach -r -d 'Attach file'
complete -c skiffllm -l file -r -d 'Attach file'
complete -c skiffllm -l export -r -d 'Export conversation as Markdown'
complete -c skiffllm -l chat-template -r -d 'Override chat template'
complete -c skiffllm -l model -r -d 'Path to a GGUF model'
complete -c skiffllm -l model-dir -r -d 'Model directory'
complete -c skiffllm -l config -r -d 'Config file path'
complete -c skiffllm -l history -r -d 'Session history file'
complete -c skiffllm -l session -r -d 'Named session'
complete -c skiffllm -l profile -r -a 'balanced fast creative code precise' -d 'Sampling profile'
complete -c skiffllm -l system -r -d 'System prompt'
complete -c skiffllm -l stop -r -d 'Stop sequence'
complete -c skiffllm -l output -r -d 'Write answer to file'
complete -c skiffllm -l prompt -r -d 'Single prompt'
complete -c skiffllm -l prompt-file -r -d 'Read prompt from file'
complete -c skiffllm -l stdin -d 'Read prompt from stdin'
complete -c skiffllm -l json -d 'JSON output'
complete -c skiffllm -l non-interactive -d 'Disable interactive shell'
complete -c skiffllm -l ctx -r -d 'Context size'
complete -c skiffllm -l batch -r -d 'Batch size'
complete -c skiffllm -l ubatch -r -d 'Physical batch size'
complete -c skiffllm -l reserve-ctx -r -d 'Reserved context'
complete -c skiffllm -l n-keep -r -d 'Kept turns during trimming'
complete -c skiffllm -l threads -r -d 'CPU threads'
complete -c skiffllm -l gpu-layers -r -d 'GPU layers'
complete -c skiffllm -l mmap -d 'Enable mmap'
complete -c skiffllm -l no-mmap -d 'Disable mmap'
complete -c skiffllm -l mlock -d 'Lock model memory'
complete -c skiffllm -l flash-attn -d 'Enable flash attention'
complete -c skiffllm -l no-flash-attn -d 'Disable flash attention'
complete -c skiffllm -l numa -d 'Enable NUMA optimization'
complete -c skiffllm -l kv-offload -d 'Enable KV offload'
complete -c skiffllm -l no-kv-offload -d 'Disable KV offload'
complete -c skiffllm -l temp -r -d 'Temperature'
complete -c skiffllm -l top-p -r -d 'Top-p'
complete -c skiffllm -l top-k -r -d 'Top-k'
complete -c skiffllm -l min-p -r -d 'Min-p'
complete -c skiffllm -l typical -r -d 'Typical sampling'
complete -c skiffllm -l repeat-penalty -r -d 'Repeat penalty'
complete -c skiffllm -l repeat-last-n -r -d 'Repeat window'
complete -c skiffllm -l n-predict -r -d 'Max generated tokens'
complete -c skiffllm -l seed -r -d 'Sampling seed'
complete -c skiffllm -l reset-history -d 'Reset history'
complete -c skiffllm -l no-save -d 'Disable session saving'
complete -c skiffllm -l auto-trim -d 'Auto trim context'
complete -c skiffllm -l no-auto-trim -d 'Disable auto trim'
complete -c skiffllm -l color -d 'Enable color'
complete -c skiffllm -l no-color -d 'Disable color'
complete -c skiffllm -l no-banner -d 'Hide banner'
complete -c skiffllm -l verbose -d 'Verbose logs'
complete -c skiffllm -l debug -d 'Debug mode'
complete -c skiffllm -l context-bar -d 'Show the live context usage bar'
complete -c skiffllm -l no-context-bar -d 'Hide the context usage bar'
complete -c skiffllm -l backend-info -d 'Print the active llama.cpp backends and exit'
complete -c skiffllm -l skills -d 'Allow the model to call enabled skills'
complete -c skiffllm -l no-skills -d 'Keep the model text-only'
complete -c skiffllm -l enable-skill -r -d 'Enable a skill'
complete -c skiffllm -l disable-skill -r -d 'Disable a skill'
complete -c skiffllm -a 'run model skill chat-template openai config server' -d 'Subcommand'
complete -c skiffllm -n '__fish_use_subcommand' -a openai -d 'Send a prompt to a local OpenAI-compatible server'
